- name: Catalogue installation
  hosts: catalogue
  become: yes
  tasks:
    - name: disable and enabel nodejs 18
      ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
    
    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
        