# Redis installation
- name: Redis installation
  hosts: redis
  become: yes
  tasks:
    - name: installing redis repo
      ansible.builtin.shell: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y ; dnf module enable redis:remi-6.2 -y
