- name: cart installation
  hosts: cart
  become: yes
  tasks:
    - name: disable and enabel nodejs 18
      ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    - name: creating roboshop user
      ansible.builtin.user:
        name: roboshop
    - name: recursively remove app directory
      ansible.builtin.file:
        path: /app
        state: absent
    - name: creating app directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: downloading the application
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/cart.zip
        dest: /tmp
    - name: unzipping the cart application
      ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app
        remote_src: yes
    - name: install dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app
    - name: copying cart service
      ansible.builtin.copy:
        src: cart.service
        dest: /etc/systemd/system/cart.service
    - name: daemon-reload
      ansible.builtin.systemd_service:
        daemon-reload: true

    - name: start and enable cart
      ansible.builtin.service:
        name: cart
        state: restarted
        enabled: yes
